Script started on 2017年03月11日 (週六) 17時23分51秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami; pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -l
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
user.name=frankpsh
user.email=afcidk@gmail.com
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git clone https://github .com/afcidk/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m 
Script done on 2017年03月11日 (週六) 17時25分05秒
